### ISSUE TITLE
Missing file babbleNoise_resample_16K.npy on the repository

### ISSUE THREAD

**Issue by lruanova** [ahaliassos/usr#1]
Hi,  

I encountered an issue while testing your demo. It seems to fail due to a missing file named _babbleNoise_resample_16K.npy_ 

Upon investigating, I noticed that on https://github.com/ahaliassos/usr/blob/main/data/transforms.py#L457 the following path is hardcoded:
`np.load('/data/home/pingchuanma/babble_noise/babbleNoise_resample_16K.npy')`.

However, this file is not provided on the repository. I found it avaliable on: [this repo](https://github.com/ms-dot-k/AVSR) and [this drive](https://drive.google.com/file/d/15CSWCYz12CIsgFeDT139CiCc545jhbyK/view) . 

Could you clarify if I missed any steps, or, if possible, update the instructions to include details about obtaining this file?

Thanks.

**Comment by ahaliassos** [comment]
Hi,

Thanks for pointing this out! The AddNoise transform is actually not required, so I have removed it.

Please re-open this issue if you have any further issues.
